config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :users, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show], shallow: true do
    resources :stocks, only: [:index, :create, :destroy]
    resources :followees, only: [:index, :create, :destroy]
    resources :followers, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy], module: :posts
    resources :likes, only: [:create, :destroy], module: :posts
  end

  resources :questions, shallow: true do
    resources :comments, only: [:create, :destroy], module: :questions
    resources :likes, only: [:create, :destroy], module: :questions
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy], module: :answers
      resources :likes, only: [:create, :destroy], module: :answers
    end
  end

  namespace :category, shallow: true do
    resources :categories, only: [:index, :show]
  end

  # ユーザーがカテゴリーをフォローする時のルーティング。delete時、relationshipのidを取らない形にするため手動のルーティングに。
  post '/follow_category', to: "follow_categories#create"
  delete '/unfollow_category', to: "follow_categories#destroy"

  resources :best_answers, only: :create

  resources :searches, only: :index

  resources :notifications, only: :index

  resources :rankings, only: :index
end

app/models/notification.rb
class Notification < ApplicationRecord
  include CommonScope

  belongs_to :answer,   optional: true
  belongs_to :comment,  optional: true
  belongs_to :question, optional: true
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id'
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id'

  validates :visitor_id, presence: true
  validates :visited_id, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  after_action :check_notifications

  def index
    @notifications = current_user.passive_notifications.recent.
      includes(:visitor, :visited).page(params[:page]).per(10)
  end

  private

  def check_notifications
    notifications = current_user.passive_notifications.includes(:visitor, :visited)
    notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
end

app/views/notifications/_notification.html.slim
- visitor = notification.visitor
- visited = notification.visited
div class=(notification.checked ? '' : 'new_notification')
  .text-left
    = link_to image_tag(visitor.profile_image.url, size: '50x50', class: 'rounded-circle') + "#{visitor.name}さんが", user_path(visitor.id)
    - case notification.action
    - when 'follow' then
      | あなたをフォローしました
    - when 'answer' then
      = link_to 'あなたの質問', question_path(notification.answer.question.id)
      | に回答しました
    - when 'best_answer' then
      = link_to 'あなたの回答', question_path(notification.answer.question.id)
      | をベストアンサーに決定しました
    - when 'stock' then
      = link_to 'あなたの質問', question_path(notification.question.id)
      | をストックしました
    - when 'comment' then
      - case notification.comment.commentable_type
      - when 'Question' then
        = link_to '質問', question_path(notification.comment.commentable.id)
        | にコメントしました
      - when 'Answer' then
        = link_to '質問の回答', question_path(notification.comment.commentable.id)
        | にコメントしました
      - when 'Post' then
        = link_to 'つぶやき', post_path(notification.comment.commentable.id)
        | にコメントしました
    hr

app/views/notifications/index.html.slim
- provide(:title, '通知一覧')
.notification_container
  - if @notifications.present?
    - unless current_user.has_new_notifications?
      h2.text-center.py-4 新着の通知はありません
    = render partial: 'notifications/notification', collection: @notifications, as: :notification
    = paginate @notifications
  - else
    h2.text-center.py-4 通知はありません