config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :users, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show], shallow: true do
    resources :stocks, only: [:index, :create, :destroy]
    resources :followees, only: [:index, :create, :destroy]
    resources :followers, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy], module: :posts
    resources :likes, only: [:create, :destroy], module: :posts
  end

  resources :questions, shallow: true do
    resources :comments, only: [:create, :destroy], module: :questions
    resources :likes, only: [:create, :destroy], module: :questions
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy], module: :answers
      resources :likes, only: [:create, :destroy], module: :answers
    end
  end

  namespace :category, shallow: true do
    resources :categories, only: [:index, :show]
  end

  # ユーザーがカテゴリーをフォローする時のルーティング。delete時、relationshipのidを取らない形にするため手動のルーティングに。
  post '/follow_category', to: "follow_categories#create"
  delete '/unfollow_category', to: "follow_categories#destroy"

  resources :best_answers, only: :create

  resources :searches, only: :index

  resources :notifications, only: :index

  resources :rankings, only: :index
end

app/views/shared/_content.html.slim
.my-4.content_container
  p= simple_format content

app/views/shared/_error_messages.html.slim
- if model.errors.any?
  .alert.alert-warning
    ul
      - model.errors.full_messages.each do |message|
        li= message

app/views/shared/_flash.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type} text-center") 
    = message

app/views/shared/_follow_button.html.slim
  - if user_signed_in? && current_user != user
    div class="follow_button_#{user.id}"
      -if current_user.following?(user)
        = form_with url: followee_path(user.id), remote: true, method: :delete do |f|
          = f.hidden_field :user_id, value: user.id
          = f.submit 'フォロー解除', class: 'btn btn-success'
      -else
        = form_with url: user_followees_path(user_id: user.id), remote: true, method: :post do |f|
          = f.submit 'フォローする', class: 'btn btn-primary'

app/views/shared/_user.html.slim
.users_container
  .row
    .col-sm-4
      .text-left
        = render partial: 'users/user_image_link', locals: { user: user }
        = user.name
    .col-sm-8
      .row
        .col-6
          .text-center
            p 回答数 : #{user.answers.count}
            p 質問数 : #{user.questions.count}
        .col-6
          .mt-3
            = render partial: 'shared/follow_button', locals: { user: user }
  hr

app/views/shared/_users.html.slim
.row
  .col-6
    p #{user.name}
  .col-6
    = render partial: 'shared/follow_button', locals: { user: user }