config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :users, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show], shallow: true do
    resources :stocks, only: [:index, :create, :destroy]
    resources :followees, only: [:index, :create, :destroy]
    resources :followers, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy], module: :posts
    resources :likes, only: [:create, :destroy], module: :posts
  end

  resources :questions, shallow: true do
    resources :comments, only: [:create, :destroy], module: :questions
    resources :likes, only: [:create, :destroy], module: :questions
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy], module: :answers
      resources :likes, only: [:create, :destroy], module: :answers
    end
  end

  namespace :category, shallow: true do
    resources :categories, only: [:index, :show]
  end

  # ユーザーがカテゴリーをフォローする時のルーティング。delete時、relationshipのidを取らない形にするため手動のルーティングに。
  post '/follow_category', to: "follow_categories#create"
  delete '/unfollow_category', to: "follow_categories#destroy"

  resources :best_answers, only: :create

  resources :searches, only: :index

  resources :notifications, only: :index

  resources :rankings, only: :index
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/views/home/home.html.slim
.lp
  = image_tag 'sakura.jpg', class: 'lp_photo'
  .lp_container
    .row
      .col-sm-6
        .lp_item
          .text-center.font-weight-bold
            p 大学受験用Q＆Aサイト
            p わかる。受かる。繋がる。
            h2 UKARIMI
      .col-sm-6
        .lp_item
          - if user_signed_in?
            .text-center
              = link_to '質問する', new_question_path, class: 'btn btn-success mr-4'
              = link_to 'つぶやく', new_post_path, class: 'btn btn-success'
              hr
              = link_to '質問一覧', questions_path, class: 'btn btn-success mr-4'
              = link_to 'つぶやき一覧', posts_path, class: 'btn btn-success'
          - else
            .text-center
              = link_to 'ゲストユーザーとしてログイン', users_guest_sign_in_path, method: :post, class: 'btn btn-success'
              hr
              = link_to icon('fas', 'sign-in-alt') + 'ログイン', new_user_session_path, class: 'btn btn-success mr-4'
              = link_to icon('fas', 'user-plus') + '登録', new_user_registration_path, class: 'btn btn-success'
          