config/routes.rb
Rails.application.routes.draw do
  root 'home#home'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }

  namespace :admin do
    resources :users, only: [:index, :create, :destroy]
  end

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  resources :users, only: [:show], shallow: true do
    resources :stocks, only: [:index, :create, :destroy]
    resources :followees, only: [:index, :create, :destroy]
    resources :followers, only: [:index]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy], module: :posts
    resources :likes, only: [:create, :destroy], module: :posts
  end

  resources :questions, shallow: true do
    resources :comments, only: [:create, :destroy], module: :questions
    resources :likes, only: [:create, :destroy], module: :questions
    resources :answers, only: [:create, :destroy, :edit, :update] do
      resources :comments, only: [:create, :destroy], module: :answers
      resources :likes, only: [:create, :destroy], module: :answers
    end
  end

  namespace :category, shallow: true do
    resources :categories, only: [:index, :show]
  end

  # ユーザーがカテゴリーをフォローする時のルーティング。delete時、relationshipのidを取らない形にするため手動のルーティングに。
  post '/follow_category', to: "follow_categories#create"
  delete '/unfollow_category', to: "follow_categories#destroy"

  resources :best_answers, only: :create

  resources :searches, only: :index

  resources :notifications, only: :index

  resources :rankings, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Liked
  include Commentable

  belongs_to :user
  belongs_to :question

  has_many :notifications, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :likes,    as: :likable,     dependent: :destroy
  has_one  :q_and_a_relationship,       dependent: :destroy

  # バリデーション
  validates :user_id,     presence: true
  validates :question_id, presence: true
  validates :content,     presence: true, length: { maximum: 1000 }

  def is_best_answer?
    self == question.best_answer
  end
end

app/controllers/answers/comments_controller.rb
class Answers::CommentsController < CommentsController
  private

  def set_commentable
    @commentable = Answer.find(params[:answer_id])
  end
end

app/controllers/answers/likes_controller.rb
class Answers::LikesController < LikesController
  private

  def set_likable
    @likable = Answer.find(params[:answer_id])
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer, only: [:destroy, :edit, :update]

  def create
    @answer = current_user.answers.build(answer_params)
    if @answer.save
      current_user.create_notification_answer(@answer)
      flash[:success] = '回答しました'
      redirect_back(fallback_location: root_path)
    else
      flash[:danger] = '回答に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @answer.destroy!
    flash[:success] = '削除しました'
    redirect_back(fallback_location: root_path)
  end

  def edit
  end

  def update
    if @answer.update(answer_params)
      redirect_to question_path(@answer.question.id), flash: { success: '回答を編集しました' }
    else
      flash[:danger] = '編集に失敗しました'
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def set_answer
    @answer = current_user.answers.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:content, :question_id)
  end
end

app/views/answers/_index.html.slim
.answer_container
  / ベストアンサー
  - if answer.is_best_answer?
    p.text-danger.text-center.mb-3
      | #{icon('fas', 'check')}
      | ベストアンサー！
  .container
    .row
      / いいね
      = render partial: 'likes/form', locals: { likable: answer }
  .text-center
      
    / 回答部分
    .row
      .col-8
        = render partial: 'users/user_image_link', locals: { user: answer.user }
        = link_to answer.user.name, user_path(answer.user.id)
      .col-4
        - if current_user == answer.user
          = link_to icon('fas', 'edit'), edit_answer_path(answer.id), class: "edit-a-#{answer.id} mr-4"
          = link_to icon('fas', 'trash'), answer_path(answer.id), method: :delete, class: "delete-a-#{answer.id}"

    / 回答本文
    hr
    = render partial: 'shared/content', locals: { content: answer.content }

    / ベストアンサーボタン
    - if current_user == answer.question.user && !answer.question.has_best_answer?
      = form_with url: best_answers_path  do |f|
        = f.hidden_field :question_id, value: answer.question.id
        = f.hidden_field :answer_id, value: answer.id
        = f.submit 'ベストアンサー', class: "btn btn-primary best_answer_btn_#{answer.id}", data: { confirm: "一度ベストアンサーを決定すると変更できません。ベストアンサーに決定しますか？", cancel: 'やめる', commit: '決定' }, title: 'ベストアンサーの確認'
    
    / コメント一覧表示
    = render partial: 'comments/index', locals: { comments: answer.comments }

    / コメント入力フォーム
    - if user_signed_in?
      button data-toggle='collapse' data-target='#collapse_comment_answer' aria-expanded='false' aria-controls='collapse_comment' 
        p.bold_texts #{icon('far', 'comment')}コメントを投稿
      .collapse#collapse_comment_answer
        hr
        = render partial: 'comments/form', locals: { commentable: answer, comment: current_user.comments.build }

app/views/answers/_submit_form.html.slim
- if user_signed_in?
  .text-center
    = form_with model: question.answers.new, url: question_answers_path(question_id: question.id) do |f|
      = f.hidden_field :question_id, value: question.id
      .form-group
        = f.text_area :content, placeholder: '回答を入力(1000文字以内)', class: 'large_text_area', required: true, maxlength: 1000
      .form-group
        = f.submit '回答する', class: 'btn btn-primary'

app/views/answers/edit.html.slim
- provide(:title, '編集')
- if current_user == @answer.user
  .text-center
    h1.font-weight-bold.my-4 回答を編集
    = form_with model: @answer, method: :patch do |f|
      = render 'shared/error_messages', model: f.object
      .form-group
        = f.text_area :content, placeholder: '回答を入力(1000文字以内)', class: 'large_text_area', required: true, maxlength: 1000
      .form-group
        = f.submit '編集内容を送信', class: 'btn btn-primary'